DELETE http://localhost:3001/api/persons/61b6f888cbace4f7d3c706c0

###
GET http://localhost:3001/info

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "John Doe",
    "number": "0987-654-321"
}

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "John Doe",
    "number": "0987654321"
}

###
PUT http://localhost:3001/api/persons/61b6f7b1ffdca59614d68826
content-type: application/json

{
    "name": "world",
    "number": "0987-654-321"
}

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Jo",
    "number": "1234567890"
}

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "number": "0987-654-321"
}

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "John Doe"
}

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Hello WORLD",
    "number": ""
}
