DELETE http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "John Doe",
    "number": "0987-654-321"
}

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "John Doe",
    "number": "1234-567-890"
}

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "number": "0987-654-321"
}

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "John Doe"
}